"""initial migration - added LearningPath and settings

Revision ID: bb2aa01f678b
Revises: 
Create Date: 2026-04-03 00:56:35.863577

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb2aa01f678b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('learning_path', schema=None) as batch_op:
        batch_op.add_column(sa.Column('textbook', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('program', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('class_parallel', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('preferred_minutes_per_day', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('path_metadata', sa.JSON(), nullable=True))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('settings', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('settings')

    with op.batch_alter_table('learning_path', schema=None) as batch_op:
        batch_op.drop_column('path_metadata')
        batch_op.drop_column('preferred_minutes_per_day')
        batch_op.drop_column('class_parallel')
        batch_op.drop_column('program')
        batch_op.drop_column('textbook')

    # ### end Alembic commands ###
