"""auto update

Revision ID: c032ed0023f0
Revises: bb2aa01f678b
Create Date: 2026-04-04 17:31:34.944410

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c032ed0023f0'
down_revision = 'bb2aa01f678b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('social_account')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('social_account',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('provider', sa.VARCHAR(length=30), nullable=False),
    sa.Column('provider_user_id', sa.VARCHAR(length=128), nullable=False),
    sa.Column('provider_email', sa.VARCHAR(length=120), nullable=True),
    sa.Column('provider_name', sa.VARCHAR(length=100), nullable=True),
    sa.Column('provider_avatar', sa.VARCHAR(length=500), nullable=True),
    sa.Column('access_token', sa.TEXT(), nullable=True),
    sa.Column('refresh_token', sa.TEXT(), nullable=True),
    sa.Column('token_expires', sa.DATETIME(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'provider_user_id', name=op.f('uq_provider_user'))
    )
    # ### end Alembic commands ###
